import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
const calibri = localFont({
  src: [
    {
      path: "../../public/fonts/Calibri Bold Italic.woff2",
      weight: "700",
    },
    {
      path: "../../public/fonts/Calibri Bold.woff2",
      weight: "700",
    },
    {
      path: "../../public/fonts/Calibri Italic.woff2",
      weight: "400",
    },
    {
      path: "../../public/fonts/Calibri Regular.woff2",
      weight: "400",
    },
    {
      path: "../../public/fonts/Calibri Light Italic.woff2",
      weight: "300",
    },
    {
      path: "../../public/fonts/Calibri Light.woff2",
      weight: "300",
    },
  ],
  display: "swap",
  variable: "--font-calibri",
});
const georgie = localFont({
  src: "../../public/fonts/Georgia.woff2",
  display: "swap",
  variable: "--font-georgia",
});
export const metadata: Metadata = {
  title: "Global management consulting | McKinsey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${calibri.variable} ${georgie.variable}`} lang="en">
      <body>{children}</body>
    </html>
  );
}
